### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by purdy** [xurizaemon/csvimport#2]
Have you tried importing a file, say with 24,000 records? My Drupal runs with 128M memory limit and it fails when trying this approach. I've profiled the function and the `array_map` calls are using a bulk of that.

<pre>
                                              Inclusive        Own
  function                            #calls  time     memory  time     memory
  ----------------------------------------------------------------------------
  array_map                            24567  0.9527 112200904  0.9527 112200904
  fgetcsv                              24571  1.1727 71744736  1.1727 71744736
  drupal_load                            113  0.2150 29739672  0.1852 29053976
  _drupal_bootstrap_full                   1  0.3260 31547232  0.0225  3549832
  array_chunk                              2  0.0127  3308488  0.0127  3308488
  module_list                            151  0.0341  2373464  0.0126  2221056
  _drupal_bootstrap                        9  0.4048 37329128  0.0126  1802928
</pre>

**Comment by xurizaemon** [comment]
You may need to either manually increase your memory limit for the initial file parse, or to use batches to iterate through lines of the file (batch one reads lines 1-100, batch 2 reads lines 101-200 etc).

**Comment by purdy** [comment]
Thanks, @xurizaemon :+1:
