### ISSUE TITLE
You need to set $batch['file'] to the full path of the file containing your batch functions, otherwise the batch operation will silently fail

### ISSUE THREAD

**Issue by rimu** [xurizaemon/csvimport#5]
$batch = array(
    'title' => t('Importing CSV ...'),
    'operations' => array(),
    'init_message' => t('Commencing'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => '_green_civicrm_import_finished',
    'file' => dirname(__FILE__) . DIRECTORY_SEPARATOR . "green_civicrm.import_contacts.inc",
  ) ;

This might only be true of D6, not sure about 7

**Comment by xurizaemon** [comment]
D6 no longer supported anyway, but thanks for documenting this!

Hi from the distant future 😉
