### ISSUE TITLE
Support for filefield_sources module in Drupal 7

### ISSUE THREAD

**Issue by johnrigler** [xurizaemon/csvimport#6]
In Drupal 7, I see a module which lets me upload files from places other than my laptop, such as on the server itself.  This is very useful for me because I do all of my webscrape work in linux on the server using wget, curl, and shell commands.   I then end up with a CSV file on the server which hosts the drupal site.  This module currently would have my download that CSV to my laptop and then re-upload it.  The file sources module offers a hook that gives the standard file upload more options, including the ability to upload from a directory that I specify on the server.  

Here is the link to the module.  I would love to figure this out myself and upload the results, but  I am not quite there yet:

https://www.drupal.org/project/filefield_sources

**Comment by xurizaemon** [comment]
You should check out [Feeds](https://www.drupal.org/project/feeds) and related modules.

**Comment by johnrigler** [comment]
Thank you!
