### ISSUE TITLE
Update for Drupal 8

### ISSUE THREAD

**Issue by normanlolx** [xurizaemon/csvimport#7]
I came here from https://www.drupal.org/docs/7/api/batch-api/overview and I really like the existing branches. Any chance you update this module to Drupal 8?

**Comment by xurizaemon** [comment]
PR welcome, I haven't used this in several years (wrote it for Drupal 5 or 6, IDK).

Odds are there's a better solution available already!

**Comment by normanlolx** [comment]
Wow, I wonder how comes the prior commits already appear here in a dedicated branch O_o

**Comment by xurizaemon** [comment]
I merged @leymannx excellent work in response to your question!

*then realised YOU are @leymannx 😃
