### ISSUE TITLE
hey i need little help

### ISSUE THREAD

**Issue by i-m-Shahbaj** [xurizaemon/csvimport#9]
sorry but im new to drupal can you tell me from where are you using $result variable it will be a great help thanks

**Comment by xurizaemon** [comment]
I don't see a `$result` variable in the code? The description for this module is

> Example module for Drupal which imports a CSV file (then does nothing with it)

It's up to you to add the "do something with it" - best of luck!

**Comment by i-m-Shahbaj** [comment]
sorry variable name is $results can u help me here

**Comment by xurizaemon** [comment]
I'd suggest you first read the  [Batch API Documentation](https://www.drupal.org/docs/7/api/batch-api/overview) and see if the information there helps, then if you need community support try either [Drupal IRC](https://www.drupal.org/irc) or [Drupal Stack Exchange](https://drupal.stackexchange.com) - maybe read [the dos and don'ts of Drupal IRC](https://www.drupal.org/irc/dos-and-donts) first. Even better, perhaps there is a local user group you can make a connection with to seek mentoring.

Whatever medium, **a question must be phrased in a meaningful way to get any kind of answer**.

Sorry, I don't understand what you're asking, and I'm not in a position to provide free community support via Github issues.

I wish you the best on your journey of Drupal learning!

**Comment by i-m-Shahbaj** [comment]
thank you for guiding sir
